### ISSUE TITLE
UH09 - Vincular professores a disciplinas

### ISSUE THREAD

**Issue by denisonloc** [matheuscassiano/siaca-back#10]
Eu como Coordenador
Quero vincular professores a disciplinas
Para que possam recebam os horários devidamente organizados ao final do período de matrícula

**Comment by denisonloc** [comment]
#### BACK

- [x] Criar vínculo com uma ou mais disciplinas;
- [x] Criar verificação de disponibilidade do professor

**Comment by MarcusxDM** [comment]
Ainda resolvendo esse ERRO:

ImportError: cannot import name 'Professor' from partially initialized module 'autenticacao.models' (most likely due to a circular import) (C:\Users\Marcus\Documents\GitHub\siaca-back\autenticacao\models.py)
